### PR TITLE
11ty plugin

### PR DESCRIPTION
**Pull request by what1s1ove**
Docs: https://www.11ty.dev/docs/

Resolves https://github.com/webpro/knip/pull/404

PS. 404 PR 🥲

### CODE REVIEW

**Comment by webpro** [comment]
Thanks, @what1s1ove! Just a lint issue and I'm happy to merge this.

**Comment by what1s1ove** [comment]
> Thanks, @what1s1ove! Just a lint issue and I'm happy to merge this.

Ohh sorry. Fixed!

**Comment by what1s1ove** [comment]
Hey @webpro ! Should I resolve the conflicts?

**Comment by webpro** [comment]
Oh sorry, I missed this.

**Comment by webpro** [comment]
:rocket: _This pull request is included in v3.9.0. See [Release 3.9.0](https://github.com/webpro/knip/releases/tag/3.9.0) for release notes._

**Comment by webpro** [comment]
:rocket: _This pull request is included in v4.0.0. See [Release 4.0.0](https://github.com/webpro/knip/releases/tag/4.0.0) for release notes._

**Pull request merged**
