### PR TITLE
fix: isFile/isDirectory edge cases

### LINKED ISSUE #634: 5.14.0 breaks knip in git submodules
Change introduced in https://github.com/webpro/knip/commit/29a0bdc48da8b14b88afea6bf326e0a1f5fd1203 (#613) tries to open `.git/info/exclude`, but `.git` is a file when it's a submodule.

```
Error: ENOTDIR: not a directory, stat '.git/info/exclude'
    at statSync (node:fs:1659:25)
    at isFile (file:///node_modules/.pnpm/knip@5.15.1_@types+node@20.12.11_typescript@5.4.5/node_modules/knip/dist/util/fs.js:14:18)
    at parseFindGitignores (file:///node_modules/.pnpm/knip@5.15.1_@types+node@20.12.11_typescript@5.4.5/node_modules/knip/dist/util/globby.js:91:9)
    at getGitIgnoredFn (file:///node_modules/.pnpm/knip@5.15.1_@types+node@20.12.11_typescript@5.4.5/node_modules/knip/dist/util/globby.js:135:29)
    at main (file:///node_modules/.pnpm/knip@5.15.1_@types+node@20.12.11_typescript@5.4.5/node_modules/knip/dist/index.js:34:32)
    at run (file:///node_modules/.pnpm/knip@5.15.1_@types+node@20.12.11_typescript@5.4.5/node_modules/knip/dist/cli.js:23:79)
    at file:///node_modules/.pnpm/knip@5.15.1_@types+node@20.12.11_typescript@5.4.5/node_modules/knip/dist/cli.js:90:7 {
  errno: -20,
  code: 'ENOTDIR',
  syscall: 'stat',
  path: '.git/info/exclude'
}

Node.js v21.7.1
```

A similar issue exists in the lefthook plugin, but it can be disabled by setting:

```json
{
  "lefthook": {
    "config": []
  }
}
```

### PR DESCRIPTION
**Pull request by markmartirosian**
Closes #634

### CODE REVIEW

**Comment by webpro** [comment]
Thanks @markmartirosian. Yeah let's try a try-catch, this feels a bit redundant.

**Comment by markmartirosian** [comment]
@webpro done

**Comment by markmartirosian** [comment]
@webpro isn't this scenario general? Here's an illustration, '.profile' is a regular file.

```js
> const fs = require('fs')
> fs.statSync('.profile/excludes', { throwIfNoEntry: false })
Uncaught Error: ENOTDIR: not a directory, stat '.profile/excludes'
    at Object.statSync (node:fs:1659:25) {
  errno: -20,
  code: 'ENOTDIR',
  syscall: 'stat',
  path: '.profile/excludes'
}

```

**Comment by webpro** [comment]
Isn't it odd, are we being lied to by `throwIfNoEntry: false`? I guess you're not on a Node version that does not support that option yet?

Then we could just do without this option?

**Comment by markmartirosian** [comment]
@webpro yes very unexpected, I'm on `v21.7.1` and given the versions in the screenshot this seems to be the intended behavior.

Screenshot 2024-05-15 at 17 34 09

**Comment by webpro** [comment]
Thanks @markmartirosian! Good stuff.

**Comment by webpro** [comment]
:rocket: _This pull request is included in v5.17.0-canary.0. See [Release 5.17.0-canary.0](https://github.com/webpro/knip/releases/tag/5.17.0-canary.0) for release notes._

_Using Knip in a commercial project? Please consider [sponsoring me](https://github.com/sponsors/webpro)._

**Pull request merged**
