### PR TITLE
Add wireit plugin

### PR DESCRIPTION
**Pull request by mathieucaroff**

### CODE REVIEW

**Comment by webpro** [comment]
This is awesome! Thanks a lot for creating, this @mathieucaroff. 

I do need some coverage with tests before I can merge it. You could use the script described on this page to generate test and fixture files to help with this: https://knip.dev/guides/writing-a-plugin. Otherwise you can copy-paste from others (the release-it and nx plugins come to mind) or even author manually.

**Comment by mathieucaroff** [comment]
I've run the the plugin creation script and added three fixtures and tests.

Please note that when I ran `npm run test` in `packages/knip`, the output reported seven test failures -- unrelated to my changes.

**Comment by webpro** [comment]
> I've run the the plugin creation script and added three fixtures and tests.

Thanks a lot!

> Please note that when I ran `npm run test` in `packages/knip`, the output reported seven test failures -- unrelated to my changes.

That's odd. Everything should pass both locally and in CI (Windows, Ubuntu, macOS). If it passes in CI I'm happy. If you can share output I might recognize the issue, otherwise we can just leave it.

**Comment by webpro** [comment]
:rocket: _This pull request is included in v3.9.0. See [Release 3.9.0](https://github.com/webpro/knip/releases/tag/3.9.0) for release notes._

**Comment by webpro** [comment]
:rocket: _This pull request is included in v4.0.0. See [Release 4.0.0](https://github.com/webpro/knip/releases/tag/4.0.0) for release notes._

**Pull request merged**
