### PR TITLE
Fix entrypoints for Next.js plugin when using Next.js app router

### LINKED ISSUE #235: Unused exports are never detected with Next.js plugin in app router projects
https://github.com/webpro/knip/blob/838175cca9b6182cb8500ebf79a134167fd23b4e/src/plugins/next/index.ts#L16

When using the app router (where source code is in `app`), the only entrypoints possible are
- `instrumentation.{js,ts}`
- `middleware.{js,ts}`
- `app/{manifest,sitemap,robots}.{js,ts}`
- `app/**/{opengraph,twitter}-image.{js,ts,tsx}`, except for when any directory in the path starts with a `_`
- `app/**/{icon,apple-icon}-image.{js,ts,tsx}`, except for when any directory in the path starts with a `_`
- `app/**/{page,layout,error,not-found,template,loading}.{jsx,tsx}`, except for when any directory in the path starts with a `_`
- `app/**/route.{js,ts}`, except for when any directory in the path starts with a `_`
- All of those paths, but prefixed with `src/`

Right now the entrypoints in the Next.js plugin are effectively adding every single file in `app/**` as an entrypoint, which prevents Knip from catching any unused exports

### PR DESCRIPTION
**Pull request by jonahsnider**
Closes #235

### CODE REVIEW

**Comment by webpro** [comment]
Thanks @jonahsnider! Any chance you could maybe add some test coverage as well?

**Comment by jonahsnider** [comment]
Yes, I can try adding some today/tomorrow most likely.

**Comment by jonahsnider** [comment]
@webpro Added some tests, please let me know if there's anything else I should change

**Comment by webpro** [comment]
Thanks! This is great, will release shortly

**Comment by webpro** [comment]
:rocket: _This pull request is included in v2.24.1. See [Release 2.24.1](https://github.com/webpro/knip/releases/tag/2.24.1) for release notes._

**Comment by webpro** [comment]
- For next time, there's a `npm run docs` to regenerate docs
- I removed the `next-env.d.ts` as that would hide a deeper issue (#206)

**Pull request merged**
