### PR TITLE
replace globby with much faster code when gitignore enabled

### LINKED ISSUE #425: Knip walks ignored directories hundreds of times
Trying to figure out why knip runs so slowly I ran it under strace:

```
strace -fty -o /tmp/strace.txt node node_modules/.bin/knip
```

And one reason seems to be that knip scans through directories that are build products and not part of the codebase many many times:

```
grep 'newfstatat.*repo/.dummytsdir/notifications/components/EmptyState' /tmp/strace.txt      
999592 14:18:46.124631 newfstatat(23<repo/.dummytsdir/notifications/components/EmptyState>, "", 
999622 14:18:46.840144 newfstatat(26<repo/.dummytsdir/notifications/components/EmptyState>, "",  <unfinished ...>
999621 14:18:47.114195 newfstatat(23<repo/.dummytsdir/notifications/components/EmptyState>, "",  <unfinished ...>
999622 14:18:47.394684 newfstatat(25<repo/.dummytsdir/notifications/components/EmptyState>, "",  <unfinished ...>
999622 14:18:47.646888 newfstatat(25<repo/.dummytsdir/notifications/components/EmptyState>, "",  <unfinished ...>
... (repeat 150 times)
999621 14:19:23.128059 newfstatat(23<repo/.dummytsdir/notifications/components/EmptyState>, "",  <unfinished ...>
999622 14:19:23.380199 newfstatat(23<repo/.dummytsdir/notifications/components/EmptyState>, "",  <unfinished ...>
999623 14:19:23.635903 newfstatat(24<repo/.dummytsdir/notifications/components/EmptyState>, "",  <unfinished ...>
999624 14:19:23.859579 newfstatat(24<repo/.dummytsdir/notifications/components/EmptyState>, "",  <unfinished ...>
999624 14:19:24.105388 newfstatat(25<repo/.dummytsdir/notifications/components/EmptyState>, "",  <unfinished ...>
999623 14:19:24.343105 newfstatat(26<repo/.dummytsdir/notifications/components/EmptyState>, "",  <unfinished ...>
```

In total:

* knip takes 3 minutes to run. this drastically goes down if i remove build artifacts and move ignored stuff out of the repo dir
* My repo only has 820 directories and 2900 files (`git ls-files |wc -l; fd -t directory |wc -l`)
* Without respecting ignores, there's 130k directories (`find -type d|wc -l`)
* knip made 159 getdent calls, 790 syscalls total just on that one directory (that knip shouldn't care about at all)
* knip made 590000 getdent calls, 3.6 million syscalls total

This is already **after** I moved a large gitignored directory out of the root directory where knip was running for 30+ minutes and doing 200 million syscalls before I killed it.

I believe the reason is 

1. knip scans directories that are gitignored. This was mentioned in #172 and can probably considered an upstream issue in globby.
2. knip scans every single directory many (100+) times. I'm guessing this is because it calls globby many times and each of those times it recreates the gitignore list which scans all directories.

### PR DESCRIPTION
**Pull request by phiresky**
The current dir walking method has two issues:

1. gitignores are searched for and parsed for every single plugin for every single workspace package. This search is very inefficient and walks the full directory tree, without any early exiting / pruning.
2. the gitignores are applied in memory only after walking (again, no early exiting / pruning).

The reason for both is in the globby() calls.

On every globby(patterns) call, previously this happened:

1. The full repo was recursively walked with a fast-glob glob of '**/.gitignore' to find the ignore files
3. All the ignore files are parsed
4. Now the fast-glob call with the patterns given in the config is executed (not the ones in gitignore!)
5. Now afterwards, all the ignores from gitignore are filtered out in memory (in a bit buggy way)

globby is just a thin wrapper around fast-glob, and the only globby feature knip uses is the gitignore function, which has caused multiple issues in the past (That's the reason the docs recommend trying to turn off gitignore detection for performance afaik?).

With this PR, instead this happens on a globby() call:

1. The repo is walked using @nodelib/fs.walk, incrementally building the gitignore list. Files in gitignored directories are not walked (that's what fast-glob uses internally, but fast-glob doesn't support dynamic ignores (https://github.com/mrmlnc/fast-glob/issues/265)).
2. The gitignore list is cached per passed cwd so they are only ever computed and parsed once.
     
     Since I don't think there's a lib that actually supports collecting multiple gitignore I wrote a small gitignore->micromatch converter. This converter is probably not perfect, but the globby solution is also wrong (I can give details if needed).
4. fast-glob is called with the patterns and ignore list from knip itself combined with the ignore list from the gitignore files. This causes fast-glob to also do early pruning which makes walking here much faster as well.

This should fix #425 and inverse the recommendation to set `gitignore: false` . Instead, knip should now be faster when ignoring more files which makes sense.

|(Rough) Benchmark | Before | After |
|---|---|---|
|My Repo with a huge gitignored directory inside | 30+minutes (didn't wait for it to finish). > 200 million syscalls | 2:02min |
|My Repo with just build artifacts | 3:20min | 1:50min|

The reason I'm submitting this here and not to globby itself is that (a) globby is written in JS not TS and (b) has multiple other functions that would probably be affected but knip doesn't care about.

### CODE REVIEW

**Comment by webpro** [comment]
Hi @phiresky, this is fantastic! 🔥 Thank you so much for doing this.

This is such a huge win, happy to replace globby and merge your PR. I don't have an issue with maintaining that here. Just a few points:

- This pull request reveals a bug in the 11ty plugin I've fixed in that plugin in the `main` branch, another win! Any chance you could rebase on top of that?
- Not sure why `npx knip` behaves like it does on Windows (https://github.com/webpro/knip/actions/runs/7400909611/job/20151486019), I will grab an old Windows machine this afternoon and look into it.
- I looked for a related issue and only now I see your comment in https://github.com/webpro/knip/issues/172 (sorry!), but it's great if this PR fixes `EACCES` errors too.
- The rest is stylistic I can tweak any time later on.
- And it will indeed be great to remove that "performance boost" section from the docs!

**Comment by phiresky** [comment]
I've rebased this on master.

> Not sure why npx knip behaves like it does on Windows

If that's only happening since this branch then it's probably related to some path joining doing something with \ and not /. Globby I think has some logic to convert \ to / so there's probably some inconsistency now. `knip --debug` should reveal it but it's annoying to test without Windows.

> great if this PR fixes EACCES errors too.

It should fix access errors for files / directories that are in ignored directories yes. If there's an access error in a file that's part of the repo then no. (But that seems like it probably shouldn't be ignored anyways)

> to remove that "performance boost" section

Note that this _potentially can_ still decrease the performance against `gitignore: false` if the repo is fully clean anyways. Since (a) it still does an additional directory traversal to find gitignore files and (b) the number of patterns passed to fast-glob is larger especially if the gitignore files are large. The clean repo is something that rarely happens locally, but in a CI environment it's well possible.

I don't think the impact should be much though because it's a single scan that (on my larger repo) only takes <1s.  fast-glob optimizes patterns I think by e.g. parsing them into path segments and matching those faster but not sure.

**Comment by webpro** [comment]
> I've rebased this on master.

Thanks!

> > Not sure why npx knip behaves like it does on Windows
> 
> If that's only happening since this branch then it's probably related to some path joining doing something with \ and not /. Globby I think has some logic to convert \ to / so there's probably some inconsistency now. `knip --debug` should reveal it but it's annoying to test without Windows.

I have a Windows laptop right here, I'll look into it.

> > great if this PR fixes EACCES errors too.
> 
> It should fix access errors for files / directories that are in ignored directories yes. If there's an access error in a file that's part of the repo then no. (But that seems like it probably shouldn't be ignored anyways)

Yeah that's what I meant, at least users can ignore problematic dirs/files.

> > to remove that "performance boost" section
> 
> Note that this _potentially can_ still decrease the performance against `gitignore: false` if the repo is fully clean anyways. Since (a) it still does an additional directory traversal to find gitignore files and (b) the number of patterns passed to fast-glob is larger especially if the gitignore files are large. The clean repo is something that rarely happens locally, but in a CI environment it's well possible.
> 
> I don't think the impact should be much though because it's a single scan that (on my larger repo) only takes <1s. fast-glob optimizes patterns I think by e.g. parsing them into path segments and matching those faster but not sure.

Thanks, I'll benchmark a bit. But the overall win is a no-brainer 🙏

On a related note, have you seen https://github.com/fabiospampinato/fast-ignore? If not, might have some good ideas as well.

**Comment by webpro** [comment]
Easy fix up for Windows, to be continued.. Just for the record:

```diff
diff --git a/packages/knip/src/util/globby.ts b/packages/knip/src/util/globby.ts
index 1fc3ef1e..2b9fb378 100644
--- a/packages/knip/src/util/globby.ts
+++ b/packages/knip/src/util/globby.ts
@@ -37,7 +37,7 @@ function convertGitignoreToMicromatch(pattern: string, base: string) {
 
 function parseGitignoreFile(filePath: string, cwd: string) {
   const file = fs.readFileSync(filePath, 'utf8');
-  const base = path.relative(cwd, path.dirname(filePath));
+  const base = path.relative(cwd, path.dirname(path.toPosix(filePath)));
 
   return file
     .split(/\r?\n/)

```

**Comment by webpro** [comment]
When trying this on other repos, I've noticed some where indeed faster, but others were - surprisingly - slower than before.

A couple of things I tried and seem to be working well:

- Using `tiny-readdir-glob` which is like specialized for this use case is faster than `@nodelib/fs.walk`.
- The `deepFilter` works great, but `ignores` should be pro-populated with `node_modules`, otherwise the gains are basically lost. Fortunately `tiny-readdir-glob` offers the same option.

I've benchmarked by wrapping e.g. `timerify(parseFindGitignores)` and then `knip --performance`. The results are pretty significant (50-80% improvement for this particular function on various repos). I'm really curious if you see improvements on your workloads too. 

WDYT?

```diff
diff --git a/packages/knip/package.json b/packages/knip/package.json
index f6fc237d..d9b5dc16 100644
--- a/packages/knip/package.json
+++ b/packages/knip/package.json
@@ -54,7 +54,6 @@
   ],
   "dependencies": {
     "@ericcornelissen/bash-parser": "0.5.2",
-    "@nodelib/fs.walk": "2.0.0",
     "@npmcli/map-workspaces": "3.0.4",
     "@npmcli/package-json": "5.0.0",
     "@pkgjs/parseargs": "0.11.0",
@@ -71,6 +70,7 @@
     "pretty-ms": "8.0.0",
     "strip-json-comments": "5.0.1",
     "summary": "2.1.0",
+    "tiny-readdir-glob": "1.2.1",
     "zod": "3.22.4",
     "zod-validation-error": "2.1.0"
   },
diff --git a/packages/knip/src/util/globby.ts b/packages/knip/src/util/globby.ts
index 2b9fb378..8300d42c 100644
--- a/packages/knip/src/util/globby.ts
+++ b/packages/knip/src/util/globby.ts
@@ -1,13 +1,12 @@
 import * as fs from 'fs';
-import { promisify } from 'node:util';
-import { walk as _walk } from '@nodelib/fs.walk';
 import { type Options as FastGlobOptions } from 'fast-glob';
 import fastGlob from 'fast-glob';
 import micromatch from 'micromatch';
+import readdir from 'tiny-readdir-glob';
+import { GLOBAL_IGNORE_PATTERNS } from '../constants.js';
 import { debugLogObject } from './debug.js';
 import * as path from './path.js';
 
-const walk = promisify(_walk);
 type Options = {
   /** Respect ignore patterns in `.gitignore` files that apply to the globbed files. */
   readonly gitignore?: boolean;
@@ -48,23 +47,19 @@ type Gitignores = { ignores: string[]; unignores: string[] };
 
 /** walks a directory, parsing gitignores and using them directly on the way (early pruning) */
 async function parseFindGitignores(options: Options): Promise<Gitignores> {
-  const ignores: string[] = [];
+  const ignores: string[] = ['.git', ...GLOBAL_IGNORE_PATTERNS];
   const unignores: string[] = [];
-  const consideredFiles: string[] = [];
-  await walk(options.cwd, {
-    entryFilter: entry => {
-      if (entry.dirent.isFile() && entry.name === '.gitignore') {
-        consideredFiles.push(entry.path);
-        for (const rule of parseGitignoreFile(entry.path, options.cwd))
-          if (rule.negated) unignores.push(...rule.patterns);
-          else ignores.push(...rule.patterns);
-        return true;
-      }
-      return false;
-    },
-    deepFilter: entry => !micromatch.any(path.relative(options.cwd, entry.path), ignores, { ignore: unignores }),
+  const result = await readdir('**/.gitignore', {
+    cwd: options.cwd,
+    ignore: (entry: string) => micromatch.any(path.relative(options.cwd, entry), ignores, { ignore: unignores }),
   });
-  debugLogObject(options.cwd, 'gitignore files', { consideredFiles, ignores, unignores });
+  for (const filePath of result.files) {
+    for (const rule of parseGitignoreFile(filePath, options.cwd)) {
+      if (rule.negated) unignores.push(...rule.patterns);
+      else ignores.push(...rule.patterns);
+    }
+  }
+  debugLogObject(options.cwd, 'gitignore files', { consideredFiles: result.files, ignores, unignores });
   return { ignores, unignores };
 }
 const cachedIgnores = new Map<string, Gitignores>();
```

**Comment by phiresky** [comment]
You can also try the opposite, add the entryFilter to your tiny-readdir-glob implementation,something lke this:

```ts
ignore: (entry: string) => {
  if (micromatch.any(...)) return true;
  if (basename(entry)) === ".gitignore")
  // do the parseGitignoreFile steps from above to parse the gitignore and add it directly to ginores
  return false;
}
```

**Comment by webpro** [comment]
Here are some numbers. "knip" means this repo at 92c1ac0035e3a63ab4776d224d3d31f96e8bcdc8, "kadena.js" (which the "boost doc" was inspired from) is https://github.com/kadena-community/kadena.js at 06315e20c0b750867965fbe00f0e9babce8bef1b. But that doesn't matter too much, what matters most is the number of invocations and the sums/total time.

I've "timerified" `parseFindGitignores` and `ignore`/`deepFilter`.

`tiny-readdir-glob` w/ pre-populated `ignores`

knip

```
Name                            size  min     max     median  sum
------------------------------  ----  ------  ------  ------  -------
findReferences                   324    0.70  808.35    3.61  2254.22
createProgram                      2  308.56  684.66  496.61   993.21
getTypeChecker                     2   67.09  197.88  132.49   264.97
parseFindGitignores                1   72.27   72.27   72.27    72.27
glob                              24    0.00   14.09    2.08    68.77
getImportsAndExports             384    0.01    3.91    0.06    50.14
ignore                          3587    0.01    2.52    0.01    46.78

Total running time: 3.8s (mem: 454.98MB)
```

kadena.js

```
Name                             size   min     max      median  sum
-------------------------------  -----  ------  -------  ------  -------
findReferences                     268    0.06  1804.54   10.30  9157.61
createProgram                        5  294.66  1721.97  528.57  3531.50
glob                               180    0.00   107.27    6.32  1686.14
getTypeChecker                       5   65.18   369.50  110.40   760.86
load                               205    0.00   108.03    0.00   415.60
getImportsAndExports              1412    0.01     8.76    0.08   239.39
parseFindGitignores                  1  190.48   190.48  190.48   190.48
findManifestDependencies            30    0.28    23.04    3.59   151.46
ignore                           13117    0.01     3.17    0.01   143.26

Total running time: 18.1s (mem: 1921.63MB)
```

`tiny-readdir-glob` w/o pre-populated `ignores`

knip

```
Name                            size   min     max     median  sum
------------------------------  -----  ------  ------  ------  -------
findReferences                    324    0.69  834.38    3.64  2298.06
createProgram                       2  308.51  689.71  499.11   998.21
getTypeChecker                      2   65.45  173.46  119.45   238.91
parseFindGitignores                 1  163.58  163.58  163.58   163.58
ignore                          39560    0.00    2.64    0.00    77.99

Total running time: 3.9s (mem: 461.89MB)
```

kadena.js

```
Name                             size    min      max      median   sum
-------------------------------  ------  -------  -------  -------  -------
findReferences                      268     0.06  1718.21    13.54  8820.22
createProgram                         5   374.71  1758.02   495.55  3607.26
glob                                180     0.00    86.44     6.77  1784.92
parseFindGitignores                   1  1037.75  1037.75  1037.75  1037.75
getTypeChecker                        5    66.74   357.90   119.04   770.38
ignore                           230094     0.00     3.38     0.00   518.90

Total running time: 18.8s (mem: 2128.25MB)
```

`@nodelib/fs.walk` w/o pre-populated `deepFilter`

knip

```
Name                            size  min     max     median  sum
------------------------------  ----  ------  ------  ------  -------
findReferences                   324    0.70  815.89    3.75  2367.43
createProgram                      2  316.89  689.58  503.24  1006.47
parseFindGitignores                1  320.36  320.36  320.36   320.36
deepFilter                       993    0.01    3.88    0.25   298.12
getTypeChecker                     2   67.95  177.24  122.59   245.19
glob                              24    0.00   14.61    1.72    58.66

Total running time: 4.1s (mem: 437.62MB)
```

kadena.js

```
Name                             size  min      max      median   sum    
-------------------------------  ----  -------  -------  -------  -------
findReferences                    268     0.06  2014.32    11.72  9068.85
createProgram                       5   318.58  1898.07   528.95  3784.06
parseFindGitignores                 1  2962.00  2962.00  2962.00  2962.00
deepFilter                       1350     0.01    14.65     1.73  2914.62
glob                              180     0.00    84.17     5.77  1525.00

Total running time: 20.8s (mem: 2010.77MB)
```

**Comment by phiresky** [comment]
Quick question, why is `getTypeChecker` not called for the last run (kadena.js with fs.walk)?

**Comment by webpro** [comment]
I've yanked bottom lines just to reduce noise

**Comment by webpro** [comment]
@phiresky I'm very excited to get this merged and include it with the v4 release I'm preparing. Also, I'd really like to thank you for pushing this and attribute the whole pull request 100% to you (that's also why I've pasted the diffs here).

Any chance you could still give it a shot on your workload? Are you in favor of adding my changes to your PR?

**Comment by webpro** [comment]
Had to fix a few things for Windows and then some, but this is published in v4.0.0-canary.10

**Comment by webpro** [comment]
Bummer, I knew I forgot something. Linting the https://github.com/TanStack/query repository (already using Knip, with 73 workspaces) went up from 4.7 to 16.1 seconds. Going to dive into that further tomorrow.

**Comment by drodil** [comment]
You could also give backstage repo a try from the root 👌

**Comment by webpro** [comment]
The regression I've mentioned in my last comment has been fixed (and actually improved by a good margin) in `4.0.0-canary.11`.

> You could also give backstage repo a try from the root 👌

Latest `master` of this repo (with the Knip config I provided in that PR, excluding class members or it explodes):

```
$ knip --exclude classMembers --performance
...
Total running time: 44.9s (mem: 2854.41MB)
```

**Pull request merged**
