### PR TITLE
Added support for eslint.config.cjs and eslint.config.mjs files

### LINKED ISSUE #524: Support for ESLint Flat config
ESLint is introducing a [new "flat" configuration format](https://eslint.org/docs/latest/use/configure/configuration-files-new). This is feature complete but you still need to opt in to it.

I've just updated my project to use this, and Knip is now listing 1 unused file and 17 unused dependencies where it wasn't before because it doesn't understand that these are actually used by Eslint now:
```
-> % npx knip
Unused files (1)
eslint.config.mjs
Unused devDependencies (17)
@typescript-eslint/eslint-plugin   package.json
@typescript-eslint/parser          package.json
eslint                             package.json
eslint-config-prettier             package.json
eslint-formatter-mo                package.json
eslint-plugin-jest                 package.json
eslint-plugin-jest-extended        package.json
eslint-plugin-jest-formatting      package.json
eslint-plugin-no-secrets           package.json
eslint-plugin-perfectionist        package.json
eslint-plugin-pii                  package.json
eslint-plugin-prettier             package.json
eslint-plugin-security             package.json
eslint-plugin-unicorn              package.json
eslint-plugin-write-good-comments  package.json
globals                            package.json
prettier                           package.json
```

I can fix this by manually adding my `eslint.config.mjs` file to the `entry` array in my Knip config, but it would be good if I didn't need to do this:
```
import type { KnipConfig } from 'knip';

const config: KnipConfig = {
  entry: ['src/index.ts', 'eslint.config.mjs']
};

export default config;
```

Cheers

### PR DESCRIPTION
**Pull request by sazzer**
Closes #524.

### CODE REVIEW

**Comment by sazzer** [comment]
Note that I've not changed the tests because I can't get them to work locally. However, they all build fine in the Github Actions that come with the project, so that's hopeful at least :)

**Comment by webpro** [comment]
Thanks @sazzer. Happy to merge this. I do wonder why the tests don't run on your machine?

**Comment by sazzer** [comment]
> Thanks @sazzer. Happy to merge this. I do wonder why the tests don't run on your machine?

I've no idea. Locally I get this:
```
✖ failing tests:

✖ Find dependencies in lefthook v1 configuration (1.855541ms)
  [Error: ENOTEMPTY: directory not empty, rename '/Users/coxg/source/me/knip/packages/knip/fixtures/plugins/lefthook-v1/_git' -> '/Users/coxg/source/me/knip/packages/knip/fixtures/plugins/lefthook-v1/.git'] { errno: -66, code: 'ENOTEMPTY', syscall: 'rename', path: '/Users/coxg/source/me/knip/packages/knip/fixtures/plugins/lefthook-v1/_git', dest: '/Users/coxg/source/me/knip/packages/knip/fixtures/plugins/lefthook-v1/.git' }
npm ERR! Lifecycle script `test` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: knip@5.0.2
npm ERR!   at location: /Users/coxg/source/me/knip/packages/knip
```

This is a result of running the following on a clean checkout:
```
$ npm install
$ npm run build --workspace packages/knip
$ npm test --workspaces --if-present
```

All taken directly from the `.github/workflows/test.yml` file.

But the Github Actions all ran fine, so not sure what's going on there.

**Comment by webpro** [comment]
Thanks @sazzer, that `_git` is there because one test relies on a `.git` directory but nested repos not allowed from a Git perspective, so the test is [manually renaming back & forth](https://github.com/webpro/knip/blob/main/packages/knip/test/plugins/lefthook-v1.test.ts) and I guess that's what somehow went wrong on your machine.

**Comment by webpro** [comment]
:rocket: _This pull request is included in v5.0.3. See [Release 5.0.3](https://github.com/webpro/knip/releases/tag/5.0.3) for release notes._

**Pull request merged**
