### PR TITLE
Symbols reporter: output file path with line number

### PR DESCRIPTION
**Pull request by tkrotoff**
Makes it possible to open the file at the issue line number

Demo:

https://github.com/webpro/knip/assets/643434/69114379-5994-4de6-a06c-34119d1af595

### CODE REVIEW

**Comment by webpro** [comment]
Thanks @tkrotoff! This is great and I love to merge this, but I'm going to wait a little and include it in the next major to prevent any potential surprises. I promise it won't be long :)

**Comment by tkrotoff** [comment]
Thx, no problem

**Comment by webpro** [comment]
Alright, I finally released [v3.0.0-canary.0](https://github.com/webpro/knip/releases/tag/3.0.0-canary.0)

Any chance you could make `v3` (instead of `main`) the target branch? The repo is a monorepo and the files have been movef to `packages/knip`.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v3.0.0. See [Release 3.0.0](https://github.com/webpro/knip/releases/tag/3.0.0) for release notes._

**Pull request closed without merging**
