### PR TITLE
docs: add info about markdown reporter to docs

### PR DESCRIPTION
**Pull request by drodil**

### CODE REVIEW

**Comment by webpro** [comment]
Thanks @drodil! Any chance you could add a quick example Markdown output too? 😅

**Comment by drodil** [comment]
> Thanks @drodil! Any chance you could add a quick example Markdown output too? 😅

Sure :)

**Comment by webpro** [comment]
Thank you! 🙌

**Comment by webpro** [comment]
:rocket: _This pull request is included in v3.12.0. See [Release 3.12.0](https://github.com/webpro/knip/releases/tag/3.12.0) for release notes._

**Comment by webpro** [comment]
:rocket: _This pull request is included in v4.0.0. See [Release 4.0.0](https://github.com/webpro/knip/releases/tag/4.0.0) for release notes._

**Pull request merged**
