### PR TITLE
fix: improve support of commitlint configs

### PR DESCRIPTION
**Pull request by RebeccaStevens**

### CODE REVIEW

**Comment by webpro** [comment]
I'm happy to merge this, but how did you find out all of this is supported by commitlint? I can't seem to find it in their docs, do you have a link maybe?

**Comment by RebeccaStevens** [comment]
https://github.com/conventional-changelog/commitlint#config

**Comment by webpro** [comment]
> https://github.com/conventional-changelog/commitlint#config

Sorry I missed the comment/link that was already right there 🤦

**Comment by webpro** [comment]
Thanks @RebeccaStevens!

**Pull request merged**
